title: "EHMI - Enhanced Healthcare Messaging Infrastructure"
logo: /assets/images/EHMI_logo_300x300_2.png
description: "Enhanced Healthcare Messaging Infrastructure"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
version: "Version 0.9.0"
fhir_version: "EHMI"
releasenote: https://github.com/medcomdk/ehmi/releases
thisurl: https://medcomdk.github.io/ehmi/
menuurl_item1: https://medcomdk.github.io/ehmi/
menutxt_item1: EHMI Landingpage
menuurl_item2: https://medcomdk.github.io/ehmi/assets/documents/ecore/
menutxt_item2: EHMI Core
menuurl_item3: https://medcomdk.github.io/ehmi/assets/documents/eds/
menutxt_item3: EHMI EDS
menuurl_item4: https://medcomdk.github.io/ehmi/assets/documents/eer/
menutxt_item4: EHMI Endpoint Register
menuurl_item5: https://medcomdk.github.io/ehmi/assets/documents/eas/
menutxt_item5: EHMI Addressing Service
menuurl_item6: https://medcomdk.github.io/ehmi/assets/documents/egov/
menutxt_item6: EHMI Governance
