title: "EHMI - Enhanced Healthcare Messaging Infrastructure"
logo: /assets/images/EHMI_logo_300x300_2.png
description: "Enhanced Healthcare Messaging Infrastructure"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
version: "Version 0.0.1"
fhir_version: "EHMI"
releasenote: https://github.com/medcomdk/ehmi/releases
thisurl: https://medcomdk.github.io/ehmi/
menuurl_item1: https://medcomdk.github.io/ehmi/
menutxt_item1: EHMI Landingpage
menuurl_item2: https://medcomdk.github.io/ehmi/assets/documents/governance/
menutxt_item2: EHMI Governance
# menuurl_item3: https://medcomdk.github.io/MedCom-FHIR-Communication/#About
# menutxt_item3: About MedCom FHIR®© Governance
